### ISSUE TITLE
Request: do not include dependencies in the library

### ISSUE THREAD

**Issue by jfsso** [intercom/intercom-android#126]
It came to my attention that the Intercom Android SDK is unnecessarily adding a huge amount of method references. With a further look at the SDK package, I saw that you include dependencies into the library package, with 2 thirds of method references of the lib being taken up by those. As you may already be aware of, every method reference is worth saving to keep the app under that [65K reference limit](https://developer.android.com/tools/building/multidex.html) to not have an impact on performance on pre-lollipop devices.

I'd like to ask you to reconsider this packaging of dependencies inside the library. Most modern apps are likely to depend on some or most of those libraries anyways. With the exception of PhotoView, we depend on all those square libs too ;)

For reference, here's the output of [dex-method-counts](https://github.com/mihaip/dex-method-counts) for intercom. Almost 2 thirds (4000 !!!) are method references for included dependencies.
```
        intercom: 5999
            android: 1942
                blocks: 202
                    blockInterfaces: 15
                    models: 77
                nexus: 159
                sdk: 1581
                    Inbox: 64
                    activities: 29
                    annotations: 3
                    api: 172
                    attachments: 51
                    blocks: 123
                    conversation: 232
                        events: 12
                        lightbox: 16
                    gcm: 45
                    identity: 80
                    interfaces: 4
                    logger: 7
                    models: 406
                        Events: 39
                            Failure: 12
                            realtime: 4
                        api: 338
                            response: 149
                    preview: 63
                    spans: 6
                    transforms: 9
                    user: 4
                    utilities: 65
                    views: 104
            com: 2919
                google: 759
                    gson: 759
                        annotations: 6
                        internal: 478
                            bind: 287
                        reflect: 18
                        stream: 85
                squareup: 2160
                    okhttp: 1694
                        internal: 1000
                            http: 260
                            io: 18
                            spdy: 412
                            tls: 19
                            ws: 79
                        ws: 28
                    otto: 57
                    picasso: 409
            okio: 388
            retrofit: 492
                android: 7
                appengine: 7
                client: 70
                converter: 15
                http: 27
                mime: 61
            uk: 258
                co: 258
                    senab: 258
                        photoview: 258
                            gestures: 27
                            log: 25
                            scrollerproxy: 24
```

**Comment by harkin** [comment]
We had an open issue for this that might provide more context on why we decided to do this, [issue](https://github.com/intercom/intercom-android/issues/50)

There's a tradeoff between having a potentially smaller dex footprint and having reliable behaviour independent of what libraries someone using Intercom might want to use. I say potentially because not all apps do use the same stack we do. Ion and Volley are popular for networking things (many people still use apache too). Glide and Universal Image Loader are very popular for image loading, there are other event buses and with RxJava gaining popularity some people are turning away from the event bus paradigm entirely. 

It's unlikely that every app will want to use the same versions of libraries that we use. If you want Picasso 2.4.0 and we use Picasso 2.5.2 that can lead to some interesting problems. The ClassLoader will sometimes serve you the 'wrong' version and that can lead to major headaches that get tricky to debug. Where we see these conflicts happen most often is with other libraries that haven't namespaced a dependency. Something breaks in Intercom or something breaks in OtherLibrary and we get these amazingly confusing stack traces that don't make sense because a version of a dependency was loaded that we didn't expect. Or depending on how your project is set up it just refuses to build citing multiple instances of something on the classpath. 

If you use the version we provide then you're constrained in when you can update the library - relying on us to do it as part of a release. This introduces much more complexity. You as a developer need to be aware of what changed in the Intercom library and *also* what changed in every dependency we updated. If there are breaking changes in Retrofit and you're using our version, well that sucks you don't have any choice but to go fix it. 

We haven't altered any of these libraries so it is still possible for any app that uses this stack to use the versions we provide by importing `io.intercom.com.okhttp.*` and so on. In the future if we do modify a library we'll change the package name to include `modified` or something like that so developers are aware. 

We're unlikely to change this going forward. The benefits to us outweigh the disadvantages significantly, especially with tools like Proguard to remove unused methods and multidexing that lets you break the 65k limit now.

**Comment by jfsso** [comment]
Thanks for taking the time and writing this long response, but I'm not convinced. If some app developers are not maintaining their dependencies well, it shouldn't mean that all other developers have to be penalized for that.

There should be other approaches to this problem. If some developers really want this you can make your build scripts to generate a fat-jar for them, but not for everyone. See [stetho](https://github.com/facebook/stetho)'s approach. They do generate a fat-jar for those who want it, but they don't make it the only choice for everyone.

Anyways. For those that can't accept a fat-jar, here's a simple script to force intercom-android into a diet: https://github.com/jfsso/intercom-android-slim . Make sure you have all the dependencies declared in the build script when adding the generated aar to your project.

**Comment by trevjonez** [comment]
Why not offer both options. Assuming you are running your build with the android gradle plugin a very viable option would be to have a repackaged lib flavor and a transitive flavor.

This is really just a cop out so you don't have to support people that remain oblivious to their build dependencies. (ironic given that the concept intercom is primarily based on providing the best customer support)

A key component to your argument is that people can just use Progaurd or Multidex. In the event you use multidex and target any lower than API 21 you accept huge issues in regards to consistency due to issues with dalvik and the multidex tooling. Many of which make multidex simply not an option.

With Progaurd that might work fine in regards to doing release builds, and having the build complete under 65K with minification that is great. However on the flip side of this you simply cannot debug in a productive way on a Progaurd processed debug build. The concept that someone would suggest this indicates they have never tried to actually debug a minified build in android studio.

As I mentioned in issue #154 this approach is a dis-service to the people who actually consume your API's directly. Until your library can have a minSDK version of 21 without cutting off [~75%(as of November 2, 2015)](http://developer.android.com/about/dashboards/index.html) of the user base, your response of "Progaurd [...] and multidexing" is irresponsible. 

Limitations of the multidex support library under [Configure your apps for multidex for gradle](http://developer.android.com/tools/building/multidex.html#mdex-gradle)
