### ISSUE TITLE
GCM delay

### ISSUE THREAD

**Issue by shiami** [intercom/intercom-android#158]
We are in Taiwan, and the GCM message seems not quite instant delivered.
It cost 10~30 seconds to receive the GCM.
I think GCM is much faster than that.
Please help to deal with it.
Thank you.

**Comment by DaleCantwell** [comment]
Hi @shiami,
As we support real time messaging we need to add an artificial delay to make sure a message has not been marked as read before we send the push. If we didn't do this and a user was logged in on two devices they would be getting spammed push messages for every reply on one device even though the conversation is open on another. 
We will look into any performance increases we can make but that ruleset will always cause some degree of slowdown.
-Dale

**Comment by shiami** [comment]
Hi, I just received a notification that sent around 21 mins before.
Is that really possible or something did went wrong?

**Comment by DaleCantwell** [comment]
The only way I can check the timing is by looking at the conversation id. Could you write into Intercom using our web widget in the bottom right of intercom.io and ask for Dale to read over this and paste in the conversation id. It is not good to share the id publicly here which is why I am requesting this goes into Intercom.
Thanks
