### ISSUE TITLE
intercom-sdk:1.1.8 gives Zip Exception: duplicate entry

### ISSUE THREAD

**Issue by virengujariya** [intercom/intercom-android#162]
```Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
 java.util.zip.ZipException: duplicate entry: com/google/android/gms/internal/zzqd.class```

However, if I use intercom-sdk:1.1.4 and add SYSTEM_ALERT_WINDOW permission then it works fine.

**Comment by virengujariya** [comment]
I have ```com.google.android.gms:play-services-analytics``` dependency included as well.

**Comment by harkin** [comment]
What version of `play-services-analytics` are you using? We include `com.google.android.gms:play-services-gcm:8.1.0` for gcm, I suspect the issue is that you're using `8.3.0`. Two workarounds for this: use `8.1.0` or include `com.google.android.gms:play-services-gcm:8.3.0` (with the understanding that we can't stand behind an integration that uses version `8.3.0` of the gcm lib as we haven't fully tested that update yet)
