### ISSUE TITLE
android.app.RemoteServiceException exception from 4.x device after upgrade to 1.19

### ISSUE THREAD

**Issue by samehgerges** [intercom/intercom-android#198]
After we upgraded to Intercom 1.19 we started to notice the occurrence of below exception, We are using crittercism for crash tracking
 
## Version info
  - Intercom for Android version: 1.19
  - Android OS version: 4.4.4, 4.4.2, 4.2.2, 4.0.4
  - Android Device: many

## Steps to reproduce
 1. Try to contact end user by sending a message for customer support
 2. Application receive the push notification and deliver to intercom library
 3. Intercom library downloads avatar from https://static.intercomassets.com/avatars/
 4. Crash happens

## Logs
0	android.app.RemoteServiceException: Bad notification posted from package : Couldn't create icon: StatusBarIcon(pkg=application package user=0 id=0x7f0200f9 level=0 visible=true num=0 )
1		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
2		at android.os.Handler.dispatchMessage(Handler.java:102)
3		at android.os.Looper.loop(Looper.java:146)
4		at android.app.ActivityThread.main(ActivityThread.java:5593)
5		at java.lang.reflect.Method.invokeNative(Native Method)
6		at java.lang.reflect.Method.invoke(Method.java:515)
7		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
8		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
9		at dalvik.system.NativeStart.main(Native Method)

**Comment by DaleCantwell** [comment]
Hi @samehgerges thanks for reporting this issue. Here is a description of the what the issue is and a fix that can be implemented client side and our plans on how to prevent this issue Intercom side.

**The issue**
We ask that you pass us a resource id here: 
Intercom.client().setupGCM(token, R.drawable.ic_push_logo);
That is used to draw the push notification icon in your status bar. Unfortunately it requires a resource id so we can't get around this by requesting a bitmap or sending the logo down from the server.
``` JAVA
        NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
                .setSmallIcon(resourceId)
                .setContentTitle(title)
                .setContentText(content)
                .setContentIntent(pendingIntent);
 ```
This works fine except if the host app is updated it is possible that the resource id may no longer be the same. 

**Intercom Fix**
On our side we are going to add validation to check the resource id and use a default one if the one provided is no longer valid. We are also going to look at decoupling the setting of the registration Id and push logo so that the logo setting can be easily and safely done in the application class.

**Client Fix**
An easy solution is to make sure to always call Intercom.client().setupGCM(token, R.drawable.ic_push_logo); in your root activity to make sure you have refreshed the logo. This will only work when the app is opened however so there is still the risk of a user updating your app but not reopening and getting a push (which is probably what caused this particular crash).

Client side you can optionally add a receiver to check when the package has been updated and anytime it has you could send us an updated logo.

```
        <receiver android:name="com.myapp.UpdateReciever">
            <intent-filter>
                <action android:name="android.intent.action.PACKAGE_REPLACED"/>
                <data android:scheme="package"/>
            </intent-filter>
        </receiver>
```

``` JAVA
public class UpdateReciever extends BroadcastReceiver {
    @Override public void onReceive(Context context, Intent intent) {
        //check if you app version has changed and then call your GCM service
       //and pass on the new id and logo to us
    }
}

```

**Comment by DaleCantwell** [comment]
As of version [1.1.21](https://github.com/intercom/intercom-android/releases/tag/1.1.21) we now protect against a crash here. The fallback will be the default icon. To avoid reverting to the default icon I would suggest implementing some version of the client fix referenced above.
In our next major release setting the app icon will be even easier.

**Comment by samehgerges** [comment]
Okay, thank you @DaleCantwell, looking forward to next major release. Also we applied recommended fix and crash rate looks much better

**Comment by PeteSesto** [comment]
@DaleCantwell I found this page due to researching the same issue.  Would it be possible for you to share your fix for this?

**Comment by saurabhtanu** [comment]
have been looking for a fix for this for long and finally found something viable in your post, thanks for that in the first place.
Also I do not get the background for this, so is this an issue with the library that would be fixed going forward or it is how it is and we need to fix the issue as our end in the way you have suggested?
