### ISSUE TITLE
3.0.0-beta - SDK should be able to use shared OkHttpClient instance

### ISSUE THREAD

**Issue by bsiegel** [intercom/intercom-android#220]
The 3.0.0-beta versions of the SDK have upgraded to (a namespaced copy of) OkHttp 3. This will cause applications that also use OkHttp 3 to have multiple OkHttpClient instances running simultaneously. According to Square:
> The best practice in OkHttp 3 is to create a single OkHttpClient instance and share it throughout the application. Requests that needs a customized client should call OkHttpClient.newBuilder() on that shared instance. This allows customization without the drawbacks of separate connection pools.

## Version info
  - Intercom for Android version: 3.0.0-beta (all)
  - Android OS version: Any
  - Android Device: Any

## Expected behavior
The 3.0.0-beta versions of the SDK shares an OkHttpClient instance with the containing application.

## Actual behavior
The 3.0.0-beta versions of the SDK holds its own, separate OkHttpClient instance.

## Steps to reproduce
1. Build an app with a 3.0.0-beta version of the Intercom SDK and OkHttp 3.x
2. Launch the app
3. Notice that multiple OkHttpClients are in use

**Comment by ronocod** [comment]
Thanks for this feedback. Doing this would require that we stop repackaging OkHttp and add it as a transitive dependency, and this has caused us a lot of issues in the past. Giving developers the ability to change our OkHttp configuration could cause issues too.

We'll bear this in mind, but we can't promise this'll be possible any time soon.

**Comment by vishna** [comment]
By repackaging this SDK adds 11k methods to any project. This is a bad practice. E.g. square doesn't repackage picasso with okhttp dependencies so it can't be that hard to do. With this enormous method count you push many apps into multidex space. Multidex is bad and adds an overhead to app launch time.

**Comment by harkin** [comment]
> This is a bad practice

@vishna I disagree. It's a _different_ practice to how some other projects manage dependencies. It has pros and cons. This is a regular talking point and we've heard opinions from folks on both sides. There is a lot more context available in various issues, [this](https://github.com/intercom/intercom-android/issues/126#issuecomment-135748670) is a good starting point

**Comment by vishna** [comment]
This is a bad practice if you care about method count in your project.

**Comment by ronocod** [comment]
@vishna we're trying to strike the right balance here, which is difficult. Repackaging increases our method count but it also prevents build errors, broken functionality and crashes that are caused by version conflicts. There's been a lot of feedback from both sides about this and while our solution is not perfect, it's the best one we've come up with so far.

**Comment by ronocod** [comment]
We now offer a build of the SDK which brings in most of its dependencies transitively. You can find a guide to integrating it [here](https://docs.intercom.com/configure-intercom-for-your-product-or-site/configure-intercom-for-mobile/using-transitive-dependencies-with-intercom-for-android). If you use some of the libraries the SDK uses (e.g. OkHttp) then using this version should lower our impact on your method count. If you use this version then we highly recommend you make sure to use the same library versions as the SDK does.

Despite this, we won't be able to share our OkHttp instance because the way we configure it would affect the client's use in your app. We know this isn't the ideal case, but the configuration of it is critical to our business logic and we don't want to interfere with the way your app works.
