### ISSUE TITLE
Intercom.enablePush is not always work

### ISSUE THREAD

**Issue by emakovsky** [intercom/intercom-android#23]
When I try to enablePush sometimes I get an error "User email or user_id must be supplied". As a result push notifications don't come to my device. Traffic log:

**Comment by DaleCantwell** [comment]
This is typically caused by the ordering of the setup. Currently we would require a session to be successful before setting up push as we need a user id or email to match the gcm key with. We are currently working on a change to how this is done but for now I would recommend using the begin session success block to set up gcm.
