### ISSUE TITLE
Intercom not hiding after tapping link in chat?

### ISSUE THREAD

**Issue by MiralDesai** [intercom/intercom-android#262]
## Version info
  - Intercom for Android version: 3.0.9
  - Android OS version: 6.0
  - Android Device: Nexus 5

## Expected behavior

When I tap on a link within an intercom chat, the intercom launcher should close and action the link. This is the behaviour with the iOS SDK. Should it not be the same on Android?

## Actual behavior

Tapping a deeplink to an activity url: "com.app://home?d=WHATEVER"

The deeplink opens the correct activity, but it opens it above the intercom launcher, rather than closing it first.

-------------------

On iOS the intercom launcher closes and the deeplink follows through, however this is not the case on Android. Is this a bug in intercom? Also, is it possible for me to detect in intercom when a link is tapped? Then I could close the launcher myself.

**Comment by ronocod** [comment]
This is because on iOS our Messenger exists in a separate UIWindow in front of the application so we need to dismiss it to follow the deep link. On Android we can follow the deep link in a new Activity so we don't need to dismiss the Messenger. This also allows the customer to navigate back to the Messenger using the back button if they want to.

We don't have a way of detecting when a link is tapped right now.

**Comment by MiralDesai** [comment]
Fair enough, makes sense.
