### ISSUE TITLE
Intercom library uses 32,594 methods

### ISSUE THREAD

**Issue by alexblack** [intercom/intercom-android#287]
The basic limit for an Android app is 65,536 methods, it looks like Intercom uses about 50% of that space for itself.  

Can that be pruned down at all?

http://www.methodscount.com/?lib=io.intercom.android%3Aintercom-sdk%3A3%2B

**Comment by harkin** [comment]
Hi @alexblack,

The footprint of 'our' code is fewer than 4,000 methods. The rest all comes from the Android support libraries and their dependencies. All of that is reusable if someone uses the Android support libraries in their own app and we believe many app developers do use them. This is distributed without stripping unused methods (via Proguard for example) so if you have that enabled in your project the footprint will shrink too.

Method count is a big concern in the Android community and we're cognisant of how we use ours. There isn't a great deal we can do to minimise the ~28k methods from the support stack that is useful for developers short of not using them and we're happy to make that tradeoff, given most people also use them so the impact is 28k overall instead of 28k*2.

Of the 4k methods that make up the Intercom code there are small things we're working on to optimise our footprint but there's nothing major on the horizon that'll move the needle significantly. For what the library provides, our Messenger on Android and all that entails, we think we're doing pretty well.

**Comment by alexblack** [comment]
👍 

After enabling multidex for debug only I can now build again using Intercom.  Our app was at 52k methods before integrating with Intercom.
