### ISSUE TITLE
Cant attach files 

### ISSUE THREAD

**Issue by Nutomic** [intercom/intercom-android#296]
Clicking the attach button has no effect, so it's not possible to attach files to a chat.

## Version info
  - Intercom for Android version: 3.0.17
  - Android OS version: 7.1
  - Android Device: LG G4

## Expected behavior
Clicking the attach button should bring up a file selector.

## Actual behavior
Nothing happens.

## Steps to reproduce
 1. Open Intercom (via `Intercom.client().displayMessenger()`)
 2. Open a chat
 3. Click on attach button

**Comment by harkin** [comment]
Hi @Nutomic, thanks for the bug report.

Do you have the `READ_EXTERNAL_PERMISSIONS` permission in your app? I can reproduce this by removing that permission. We used to hide the attachment icon if we didn't have the correct permissions so this is a regression (unsure when it was introduced right now) and will be fixed in the next version.

**Comment by harkin** [comment]
Not a regression after all, this is looking like it was a small change in the Android platform that broke behaviour we expected around when the dialog asking for permission pops up on Marshmallow+ devices. With hindsight the behaviour seemed a little weird.

**Comment by Nutomic** [comment]
Right, that fixed it. Thanks :)

**Comment by DaleCantwell** [comment]
The release https://github.com/intercom/intercom-android/releases/tag/3.0.18 hides the attachment button if it the permission is not available.
