### ISSUE TITLE
FloatingActionButton and CoordinatorLayout

### ISSUE THREAD

**Issue by jerome-fox** [intercom/intercom-android#339]
## Version info
  - Intercom for Android version: 3+
  - Android OS version: all
  - Android Device: all

## Expected behavior

Intercom is shown as a FloatingActionButton but It doesn't have the same behavior.
When we use the NavigationDrawerActivity's template, Intercom is not added in the CoordinatorLayout so when a SnackBar is shown, Intercom doesn't follow the design.

## Actual behavior

![before](https://cloud.githubusercontent.com/assets/24386674/25477172/e97a9038-2b3c-11e7-8841-cdc23f1ba9a0.png)

![after](https://cloud.githubusercontent.com/assets/24386674/25477184/edee172a-2b3c-11e7-8e7c-7ea65c0a0044.png)

## Steps to reproduce

 1. Create a NavigationDrawerActivity project
 2. Change in the layout 'app_bar_main.xml' the 'layout_gravity' of the FloatingActionButton to 'bottom|start'
 3. Add Intercom in the class 'MainActivity.java':

```java
Intercom.initialize(getApplication(), getString(R.string.intercom_api_key), getString(R.string.intercom_app_id));
Intercom.client().setLauncherVisibility(Intercom.Visibility.VISIBLE);
Intercom.client().registerUnidentifiedUser();
```

**Comment by ronocod** [comment]
The Intercom button there is not an actual FloatingActionButton object, it's a standard Button that we made to look like a FloatingActionButton. We couldn't use a FAB in this case because it only works inside AppCompat Activities.

Even if we made it a real FAB it wouldn't fix your issue as the button lives in a separate content view in your Activity, so it wouldn't be able to interact with the CoordinatorLayout.

We'll look into a fix for this and see if we can handle this situation better.

**Comment by DaleCantwell** [comment]
Hi @jerome-fox as of 3.2.2 we have added the ability to call `setBottomPadding();`

You could add a callback to your snack bar and increase and decrease the bottomPadding in `onShown` and `onDismissed`
eg.

```JAVA
snackbar.addCallback(new Snackbar.Callback() {
    @Override
    public void onDismissed(Snackbar snackbar, int event) {
        Intercom.client().setBottomPadding(0);
    }
    @Override
        Intercom.client().setBottomPadding(<ADDITIONAL_PADDING_FOR_SNACKBAR>);
    }
  });
```
I'm going to close out this issue but let me know if you run into any issues with the new API.

**Comment by jerome-fox** [comment]
Thanks, it works !
