### ISSUE TITLE
Fcm notification received 2 times when app in background

### ISSUE THREAD

**Issue by ZebPayDhruvil** [intercom/intercom-android#343]
## Version info
  - Intercom for Android version: 3.0.21
  - Android OS version: Not specific to version
  - Android Device:Not specific to version

## Expected behavior
Push should not be handled  by intercom
## Actual behavior
Push are being handled by intercom receiver
## Steps to reproduce
 We have not setup intercom receiver , not added any key nor called  Intercom.client().handlePushMessage();

Even though push is received by intercom FCM
One push sent by our app , other by intercom manager.

**Comment by DaleCantwell** [comment]
Hi @ZebPayDhruvil 

Could I get some more information on the issue here. 

From what I gather here:
- you have included the intercom-sdk-fcm library in your project
- you have put your FCM Server key in the Intercom settings
- you have the match google-services.json file in your project

That is all we need for Intercom to get a device token for that user and set up its push receiver.

Am I correct in saying your own app has also setup FCM? 
Do you get 2 push notifications when you send a push message from Intercom or from your other push setup?

If your app is drawing Intercom push notifications we explain how to solve that here https://developers.intercom.com/docs/android-fcm-push-notifications#section-step-7-using-intercom-with-other-fcm-setups-optional

Intercom should not draw push notifications from your own push setup as we check if the payload contains an Intercom-SDK identifier. If we are drawing your own apps push notification would it be possible for you to grab a screenshot of how it appears to help us understand what's happening better?

**Comment by ronocod** [comment]
@ZebPayDhruvil can you give us any more information on this?

**Comment by DaleCantwell** [comment]
@ZebPayDhruvil we haven't heard back from you in a while now. I'm going to close out this issue but let us know if the issue is persisting by contacting our support team using the messenger at [Intercom](https://www.intercom.com/)
