### ISSUE TITLE
Crash for vibrate permission.

### ISSUE THREAD

**Issue by PaNaVTEC** [intercom/intercom-android#43]
I'm having this crash:

```Fatal Exception: java.lang.SecurityException
Requires VIBRATE permission```

Maybe you need to add this permission to the library manifest

**Comment by DaleCantwell** [comment]
HI,
Thanks for reporting this issue to us. While we don't explicitly try to vibrate the device I believe this is caused by the creation of our gcm notifications. We will request the Vibrate permission in our next major release to prevent this crash. To fix the crash in the short term you can add the following permission to your own manifest file
    <uses-permission android:name="android.permission.VIBRATE"/>
Thanks,
Dale

**Comment by PaNaVTEC** [comment]
Hi @DaleCantwell you explicitly try to vibrate the device when you do:

```java
setDefaults(DEFAULT_VIBRATE | ...); or setDefaults(DEFAULT_ALL)
```
