### ISSUE TITLE
Messages get displayed beneath other View elements

### ISSUE THREAD

**Issue by hbanzon** [intercom/intercom-android#461]
For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 4.1.2
  - Android OS version: 6.0
  - Android Device: LG Nexus 5X

## Expected behavior
Intercom messages should appear above View elements

## Actual behavior
Intercom messages appear under View elements

## Steps to reproduce
 1. Send a message to your users
 2. Open the android app
 3. See image attached
![imageedit_2_4568366058](https://user-images.githubusercontent.com/716710/34260629-a1c2c018-e634-11e7-85c2-101946850448.png)

## Logs

**Comment by bboyle18** [comment]
Hi @hbanzon 👋 

Thanks for getting in touch.
From your screenshot, it looks like the Intercom snippet is behind your tabbar and also behind the alertview ("Your letter has been sent"). I would expect that its ok for the alertview to appear on top of all other UI elements.
With regards to the tab bar, the best approach is to have Intercom snippets positioned above the tab bar, so that it doesn't interfere with it. There is a method `setBottomPadding()` that you can use to position Intercom snippets correctly above the tab bar. This should solve your problem for you.

See [this issue](https://github.com/intercom/intercom-android/issues/322) for further reference.

Feel free to reopen this issue if you are still having problems after this.

Cheers

Brian

**Comment by hbanzon** [comment]
Brian,

Thank you for the quick response.  This is actually a RecyclerView with
CardViews as the RowItem elements.

I see this consistently happening for places i have a recyclerview.

Thanks,

Hino Banzon

**Comment by hbanzon** [comment]
@bboyle18 can we reopen this issue with my issue above?

Thanks,
Hino

**Comment by bboyle18** [comment]
Ok, thanks for clarifying. 
Is it possible that you are adding this `RecyclerView` after you initialise Intercom?

**Comment by bboyle18** [comment]
Is the Intercom in-app view already rendered on screen at this point or when an in-app arrives does it render itself behind the `RecyclerView`?

**Comment by hbanzon** [comment]
The view is already rendered once the Intercom in-app message arrives including the recyclerview.

**Comment by hbanzon** [comment]
By the way, I updated to version 4.1.6 of the Android SDK, and I still notice the same issue.

Thanks,
Hino

**Comment by bboyle18** [comment]
Ok, thanks for clarifying all this. It certainly sounds like a bug. Any further screenshots or videos you have of this would help us a lot in diagnosing the root cause and fixing it.
We'll start looking into this today but there probably won't be a new release of the messenger until January as we are closed for the Christmas break.

Cheers

Brian

**Comment by hbanzon** [comment]
@bboyle18 

Thank you I will try to upload a video soon.

Thanks,
Hino

**Comment by hbanzon** [comment]
HI @bboyle18 

Attached is a video of how its behaving in our application.  Notice that the IAMs will appear in other screens and then be hidden. But on the first screen, the IAM will display behind our views after they have already rendered.  The video is zipped in and in MP4 format.

Thanks,
Hino

[2017_12_21_13_29_42.mp4.zip](https://github.com/intercom/intercom-android/files/1580222/2017_12_21_13_29_42.mp4.zip)

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
