### ISSUE TITLE
Glide: Failed to find GeneratedAppGlideModule

### ISSUE THREAD

**Issue by Mathbl** [intercom/intercom-android#470]
## Version info
  - Intercom for Android version: 4.1.6
  - Android OS version: any
  - Android Device: any

## Expected behavior
I recently started using Glide in my app, and i'm encountering an issue where I have this warning showing in logcat.
```java
Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
``` 
I originally thought that I had forgot a step in my setup of Glide, but after investigating, everything seemed fine. So I opened this issue on Glide's Github repo, because I first thought it might be related. But after investigating, it seems to be a warning that comes from a (potential) conflict with intercom.

Here's the issue I opened:
https://github.com/bumptech/glide/issues/2817

This is how I include intercom at the moment
`implementation('io.intercom.android:intercom-sdk:4.1.6') { transitive = true }`

I'm not sure if i'm doing something wrong with the inclusion of the library. Any ideas? Thanks!

**Comment by skylerwshaw** [comment]
Our documentation for including Intercom and handling dependencies transitively is here:
https://docs.intercom.com/using-transitive-dependencies-with-intercom-for-android
Specifically, you should use our `base-transitive` version:
`compile 'io.intercom.android:intercom-sdk-base-transitive:4.+'`

From https://github.com/intercom/intercom-android#dependency-graph:
>If you use some of the repackaged libraries in your app, you may want to use a build that depends on them transitively. A guide to using this build can be found [here](https://docs.intercom.com/using-transitive-dependencies-with-intercom-for-android). Using this build involves more work as you need to make sure your app uses the correct version of each library.

Intercom currently requires Glide `4.1.1`. Your issue on the Glide repo says you're using `4.5.0`. If you're choosing to manually handle dependencies, you may incur conflicts if your dependencies don't match the [dependency graph](https://github.com/intercom/intercom-android#dependency-graph). If you don't want to manage this, you should consider using our standard non-transitive flavor of the Intercom SDK.

**Comment by Mathbl** [comment]
Great! Keep me updated and tell me if I can provide any more information.

**Comment by sjudd** [comment]
This happens because Glide does some reflection to find the generated Glide module that contains whatever configuration the user has specified in Glide's AppGlideModule and LibraryGlideModule. When you repackage Glide and change the package name that Glide looks for, this error message will appear because the generated Glide module will always appear in the original package. 

The good news is that for the user's copy of Glide, everything works as expected. The bad news is that it's not possible for your users to configure the repackaged version of Glide you're using in your library. That means you probably have two different disk cache instances using the same directory as well as multiple copies of Glide's memory cache and bitmap pool in any application that uses this. 

The disk cache conflict is probably the most serious potential problem. I'm not actually sure what happens when you have two instances trying to write to the same transaction log simultaneously. I'd guess that if it were catastrophic you'd have heard something by now.

The memory cache/bitmap pool issue may not be so bad if you're careful about clearing them out whenever the user exits the screens controlled by your library. The worst case is that the application will inadvertently use 2x the memory they expect to hold Bitmaps because there's one copy of these classes in the repackaged version of Glide and one copy in the normal version.

Since you're repackaging anyway, to remove the error message, you can probably add an AppGlideModule to your library (normally not allowed). You could also then use that AppGlideModule to move the default disk cache location for your library and choose smaller memory cache and bitmap pool sizes. Although that would normally break users' ability to specify Glide modules in their applications, repackaging makes that moot.

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
