### ISSUE TITLE
Re-registering a user while already registered

### ISSUE THREAD

**Issue by ahaverty** [intercom/intercom-android#471]
## Version info
  - Intercom for Android version: 4.1.6
  - Android OS version: 8.0.1
  - Android Device: Nexus 6P

## Expected behavior
Intercom library cross references the current registered user ID with the new attempted user ID, and resets/logs out and registers the new user ID if they don't match.

## Actual behavior
I/Intercom: Failed to register user. We already have a registered user. If you are attempting to register a new user, call reset() before this.

## Steps to reproduce
 1. Register as an identified user with a custom user ID
 2. In a later activity, register as an identified user with a different custom user ID

## Logs
I/Intercom: Failed to register user. We already have a registered user. If you are attempting to register a new user, call reset() before this.

## Context
I'm using firebase and firebase's authentication, initially starting my users as "anonymous" firebase users, who have firebase user IDs.
Then after they log in, they are given a new account with a different user ID.
With intercom, I've been registering with custom user IDs at every authentication change by calling:
`Intercom.client().registerIdentifiedUser(Registration.create().withUserId(currentUser.getUid()));`
and on user initiated logouts, I've been logging out with:
`Intercom.client().logout();`

However, I didn't realise a .logout() call was needed between registering my anonymous user and later registering my signed in user. As a result, my signed in user is left registered with the old anonymous user ID.

I'd like to see the intercom library handle the reset within the register call for a few reasons:
- Abstract it from my code
- Avoid unnecessary resets, as I outlined in "steps to reproduce"
- Handle strange edge-cases with logouts where a user may not have initiated the logout

**Comment by ahaverty** [comment]
Also, note the latest library logs are still saying "reset()" which is deprecated.

**Comment by ahaverty** [comment]
I believe https://github.com/intercom/intercom-android/issues/432 is similar enough to this issue. It just seems like something the library should be handling internally, and let devs freely call register without having to worry 👍 

(_It doesn't look like we have access to the current user details/ID, so I'm not even sure where to begin besides calling .reset() before every register call._)

**Comment by skylerwshaw** [comment]
@ahaverty This is a feature request to have the Intercom library handle user lifecycle in a different manner. We believe that similar to the pattern of most authentication systems, if you're logged into a service, you should explicitly log out of it. Changing to the ability to bash on top of currently registered users is harder for application developer to model and reason about their user lifecycle, and would likely lead to decreased satisfaction with Intercom's SDK due to reported issues of mixed user data.

In your particular case once you have the initial registered user, you can update the user_id for that user. This has the added benefit of not doubling your user count in Intercom, and retaining the user data/events for them:
```
UserAttributes userAttributes = new UserAttributes.Builder()
        .withUserId("1516794455")
        .build();
Intercom.client().updateUser(userAttributes);
```

Let us know if you have any other questions, here or through the Intercom messenger on your Intercom app dashboard.

**Comment by skylerwshaw** [comment]
>I believe #432 is similar enough to this issue
You are not calling `registerUnidentifiedUser` according to the above, so it does not appear to be associated.
