### ISSUE TITLE
3rd party dependencies

### ISSUE THREAD

**Issue by hvisser** [intercom/intercom-android#50]
The SDK requires a bunch of external libraries, which is problematic for me as a developer to integrate:
* Some libraries may conflict with libraries that I am using in my app
* I do not want to be dependent on the versions required by the SDK. For example: if my app also uses Gson, I'm now basically stuck on the version that the SDK is using.

Other than the android-support dependency and the Google Play Services GCM dependency I would like to see 3rd party libs to be repackaged and internal to the SDK, to prevent any conflicts with the app code.

**Comment by mderazon** [comment]
Agree, I'm really excited about intercom SDK but our app depends on nearly all of these dependencies already and we can't afford any conflicts.
Therefor integrating this is not possible for us.

**Comment by DaleCantwell** [comment]
Thank you for the feedback. We understand that our dependancy requirements can cause integration difficulties. There are some side effects to us repackaging our dependencies. 
For example if we package gson as intercom-gson in the sdk and the host application is using gson there will be a lot of duplicate methods which is bad for our impact on 65k method limit (https://developer.android.com/tools/building/multidex.html#about). 
It is something we will address in v1.0 but in the meantime we will make sure we are always using the most up to date version of those dependencies.

**Comment by hvisser** [comment]
Just stressing again that the integration of this SDK is pretty intrusive in terms of API level requirements, permissions and dependencies. Any work going on to resolve that?

**Comment by DaleCantwell** [comment]
@hvisser what API level requirements, permissions and dependencies are you finding intrusive?

**Comment by hvisser** [comment]
API level 15 can be problematic, for example our app is still on 14. Including gson, okhttp, otto, retrofit and picasso as dependencies is just not right for an SDK and introduces potential conflicts. I think you should both trim these dependencies and repackage what you do need. Even if that means that the dex limit might be reached, now that we have multidex I rather have the option to go for that or not use intercom at all.

The `android.permission.SYSTEM_ALERT_WINDOW` might freak some users out, since it's not a very common permission for apps to ask.

We are currently calling intercom through the REST API which is mostly working fine, except for not being able to specify Android specific properties. 

One other suggestion is that I personally think it would make sense to split the SDK in two parts: 1. to support the events, user sessions (non-ui) and 2. for additional UI stuff.

**Comment by DaleCantwell** [comment]
Thanks for your feedback. Previously we used to have two versions of the Android integration: one data only and one UI but maintaining the two versions is very time consuming and adds additional risks. we opted for allowing developers to optionally hide the visuals with the following method Intercom.client().setVisibility(Intercom.GONE).

Regarding supported versions, we compile on API 9 and up, we only show visuals on API 15. We did this so that we wouldn't force apps to change their minimum targeted version. https://github.com/intercom/intercom-android#supported-versions

We require android.permission.SYSTEM_ALERT_WINDOW to draw the messenger over the host app. It will appear in the other section of permissions as "draw over other apps". It is in popular apps such as Facebook Messenger and Viber. To reduce the permissions we request we have made as many as possible optional. https://github.com/intercom/intercom-android#permissions

The mobile team discussed packaging dependencies and we have looked into developer feedback. Some developers will be fine with multidex but others who used the same libraries preferred to not double the count. A solution here to avoid conflict is to not set transitive to true and then include the versions of libraries you wish to use.

**Comment by hvisser** [comment]
Yeah well, transitive won't work of course if the SDK needs those classes and will probably just crash in that case, thanks anyway.

**Comment by DaleCantwell** [comment]
If you remove a dependency that we need it will certainly crash but if you are looking to use a different version to solve a conflict it shouldn't be an issue (unless there was large change to said library that would break our integration). If there is a particular library you are having issues using with our integration we would be happy to help, perhaps contacting us in Intercom would be handier to solve specific issues.

**Comment by IlyaEremin** [comment]
@DaleCantwell for what need gcm from google play services? Is it for analytics or for push notifications? Can I use these code: 

    compile ('io.intercom.android:intercom-sdk:1.0.4@aar') {
        transitive = true
        exclude group: 'com.google.android.gms'
    }
If I need only analytics?

Also, it is obvious need to rid of much of dependency. For example, I use `jackson` for json parsing and  `com.squareup.retrofit:converter-jackson` because it is faster than `gson`, so I have to have two json parser... 
Also, I use old play-services for map to support more devices (some devices do not have latest play services) and I faces with `more than one library with package name "com.google.android.gms"`. The same about okhttp. Why not standard android http client?
I think you have to use as much android build-in functionality as posible.

**Comment by harkin** [comment]
@IlyaEremin sorry for the delay in responding, didn't see your comment

We include that for GCM notifications. The latest version of the library has split GCM into it's own module so if you don't require GCM in your app you can use grab the base aar from bintray, 
``` compile('io.intercom.android:intercom-sdk-base:1.1.1@aar') {
        transitive = true
    }```

This would work for you if you require an older version of the play services library.

We did weigh up rolling our own libs for everything vs using existing libs, but it wasn't a difficult decision to use existing, proven libraries. Making our own networking solution would be reinventing the wheel; there are great solutions for java and android already (okhttp, volley spring to mind). We chose our dependencies because they're relatively small and do specific jobs very well. We aren't going to drop in new dependencies that will bloat the library we provide horribly (like guava would)

**Comment by harkin** [comment]
We are looking into repackaging our dependencies to avoid conflicts etc, I'll keep this issue updated with where that investigation leads us

We're hoping that splitting gcm into a separate module will help with some of the existing problems and cut down on permissions for those that don't want gcm.

**Comment by IlyaEremin** [comment]
@harkin ok, thanks for explonation about `intercom-sdk-base`. It is very helpful.
One more quetion about dependency: Does `picasso` need for base sdk?

**Comment by harkin** [comment]
@IlyaEremin yeah we still use picasso in `intercom-sdk-base`

**Comment by IlyaEremin** [comment]
@harkin can you tell for what? In my mind `intercom-sdk-base` is responsible for analytics and does not affect on the UI. Am I wrong?

**Comment by harkin** [comment]
@IlyaEremin sure. Base incorporates all the functionality of the library except GCM notifications. This includes being able to start, read and respond to conversations, which will have avatars and can contain images etc

**Comment by harkin** [comment]
Quick update, we're working on this. 

We're going to repackage all our dependencies except the play services and support libs. All going well our next release will have this change

**Comment by harkin** [comment]
From v1.1.3 onwards all our dependencies except play services and support libs are repackaged. Glad to finally be able to close this :)

**Comment by mauricegavin** [comment]
This is a really welcome feature. Thanks.
