### ISSUE TITLE
SDK does not support API levels < 12

### ISSUE THREAD

**Issue by keiththompson** [intercom/intercom-android#69]
I'm getting this crash upon initialisation. I suspect it's because the SDK is using <a href="http://developer.android.com/reference/android/util/LruCache.html">`android.util.LruCache`</a> rather than <a href="http://developer.android.com/reference/android/support/v4/util/LruCache.html">`android.support.v4.util.LruCache`</a>

This occurs on `0.9.5` & `0.9.6`

```
AndroidRuntime  E  FATAL EXCEPTION: main
 E  java.lang.NoClassDefFoundError: android.util.LruCache
 E      at io.intercom.android.nexus.NexusClient.<init>(SourceFile:21)
 E      at io.intercom.android.sdk.NexusWrapper.<init>(SourceFile:14)
 E      at io.intercom.android.sdk.Bridge.getNexusClient(SourceFile:62)
 E      at io.intercom.android.sdk.identity.AppConfig.update(SourceFile:116)
 E      at io.intercom.android.sdk.identity.AppIdentity.updateAppConfig(SourceFile:56)
 E      at io.intercom.android.sdk.identity.IdentityStore.setAppConfig(SourceFile:55)
 E      at io.intercom.android.sdk.api.CallbackHolder.updateAppConfig(SourceFile:113)
 E      at io.intercom.android.sdk.api.CallbackHolder.updateBaseResponseObjects(SourceFile:105)
 E      at io.intercom.android.sdk.api.CallbackHolder.access$000(SourceFile:28)
 E      at io.intercom.android.sdk.api.CallbackHolder$2.success(SourceFile:44)
 E      at io.intercom.android.sdk.api.CallbackHolder$2.success(SourceFile:41)
 E      at io.intercom.android.sdk.api.Api$3.success(SourceFile:180)
 E      at io.intercom.android.sdk.api.Api$3.success(SourceFile:176)
 E      at retrofit.CallbackRunnable$1.run(SourceFile:45)
 E      at android.os.Handler.handleCallback(Handler.java:587)
 E      at android.os.Handler.dispatchMessage(Handler.java:92)
 E      at android.os.Looper.loop(Looper.java:123)
 E      at android.app.ActivityThread.main(ActivityThread.java:3687)
 E      at java.lang.reflect.Method.invokeNative(Native Method)
 E      at java.lang.reflect.Method.invoke(Method.java:507)
 E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
 E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
 E      at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Harkin** [comment]
That would cause a crash. I can't reproduce this on a gingerbread device so something a little odd is happening and it might not be a trivial fix. I'm going to dig into it.

**Comment by keiththompson** [comment]
On closer inspection it's actually initialising fine, it's `Intercom.client().registerUnidentifiedUser();` that's causing the crash.

**Comment by Harkin** [comment]
:+1: I've found the issue, we'll have a fix out today

**Comment by keiththompson** [comment]
Awesome. 
Thanks @Harkin :+1:

**Comment by DaleCantwell** [comment]
@keiththompson the issue was part of our real time integration not supporting v4 LruCache as you suspected. We have actually decided to stop supporting anything below API level 14. We are going to keep the ability to target API 9 and up but there will be no Intercom functionality.
We have been considering this for some time: our reasoning being we wanted to provide the full functionality to all registered Android users. In our current state 2.3 users will be registered but couldn't use any of the messaging interface meaning any messages you send them will not be received on that device.  This problem is even worse if you integrate Intercom on Android only, that would result in a subsection of users would have no way of ever receiving your messages. 

I hope this won't cause any issues with your integration.
