### ISSUE TITLE
Impossible to use Intercom with Google Analytics

### ISSUE THREAD

**Issue by fliped** [intercom/intercom-android#78]

**Comment by Harkin** [comment]
@fliped could you give some more details please, like what actually happens when you try to use both?

**Comment by fliped** [comment]
I trying to use new version Google Analytics V4 and i need new version of play services for this (compile 'com.google.android.gms:play-services:7.3.0')
after adding your lib by marven
repositories {
    maven {
        url 'https://dl.bintray.com/intercom/intercom-maven'
    }
}
    compile('io.intercom.android:intercom-sdk:1.0.0@aar'){
        transitive = true
    }
i receive error (Error:(25, 13) error: cannot find symbol class GoogleAnalytics) and if i try add to my gradle compile 'com.google.android.gms:play-services:7.3.0' i receive UNEXPECTED TOP LEVEL EXEPTION 

In your documentation( http://docs.intercom.io/Install-on-your-mobile-product/installing-intercom-for-android ) you use compile 'com.google.android.gms:play-services-base:7.3.0' , may be this is problem?

**Comment by Harkin** [comment]
Oh woops, our docs aren't correct there :( we actually use `'com.google.android.gms:play-services-gcm:7.3.0'` and we've updated the docs now. The version of the play services library that we use doesn't have Google Analytics in it which is why you can't find it. 

I *can't* reproduce that top level dex exception locally in a test app with a dependencies block of 
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile ('io.intercom.android:intercom-sdk:1.0.0@aar') {
        transitive = true
    }
    compile 'com.google.android.gms:play-services:7.3.0'
}
```
Google Analytics is present and works. 

What you could try is not including dependencies through the sdk and instead specifying them yourself like this: 
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile ('io.intercom.android:intercom-sdk:1.0.0@aar')
    compile 'com.google.android.gms:play-services:7.3.0'
    compile 'com.android.support:support-v4:22.1.1'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.squareup:otto:1.3.7'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-ws:2.3.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
}
```
This is fine but if you use this solution going forward you'll need to take on responsibility for keeping them up to date if we require a higher version in Intercom.

**Comment by fliped** [comment]
Sorry, it was my problem

**Comment by Harkin** [comment]
:+1:

**Comment by touficSl** [comment]
@harkin

Hello Dear,

I have the same problem
I have these 2 sdk versions :
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.google.android.gms: play-services-analytics: 10.2.1' // Google Analytics
    compile 'io.intercom.android:intercom-sdk:3.+' // Intercom
}
When I compile these 2 sdk at the same time, the application crashes
I tried to use 
compile ('io.intercom.android:intercom-sdk:3.+') {
        transitive = true
    }
but didn't work

can you please help me to fix it ?
